---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/connects-to: "villains-db,otel-collector"
    app.openshift.io/vcs-ref: main
    app.quarkus.io/commit-id: dc5044e4635b639b7165a38a9a97fece36f9427c
    app.quarkus.io/build-timestamp: 2023-03-17 - 16:07:52 +0000
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: {{ .Values.app.version }}
    app.kubernetes.io/part-of: villains-service
    app.kubernetes.io/name: rest-villains
  name: rest-villains
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-villains:java11-latest
      importPolicy: {}
      name: java11-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-villains:java17-latest
      importPolicy: {}
      name: java17-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-villains:native-latest
      importPolicy: {}
      name: native-latest
      referencePolicy:
        type: Source
