---
app:
  serviceType: ClusterIP
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 5
    httpGet:
      path: /q/health/live
      scheme: HTTP
      port: 8084
  image: rest-villains:native-latest
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 768Mi
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 5
    httpGet:
      path: /q/health/ready
      scheme: HTTP
      port: 8084
  version: native-latest
