---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- range $key, $val := .Values.app.labels }}
{{ indent 2 $key }}: {{ $val | quote }}
{{- end }}
  name: rest-villains-config-creds
data:
  quarkus.datasource.username: c3VwZXJiYWQ=
  quarkus.datasource.password: c3VwZXJiYWQ=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- range $key, $val := .Values.app.labels }}
{{ indent 2 $key }}: {{ $val | quote }}
{{- end }}
  name: villains-db-config
data:
  POSTGRESQL_DATABASE: dmlsbGFpbnNfZGF0YWJhc2U=
  POSTGRESQL_USERNAME: c3VwZXJiYWQ=
  POSTGRESQL_PASSWORD: c3VwZXJiYWQ=
type: Opaque
