---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/connects-to: "fights-db,fights-kafka,apicurio,rest-villains,rest-heroes,otel-collector"
    app.openshift.io/vcs-ref: main
    app.quarkus.io/commit-id: e6b908a2aad15d5f15e203fc2a7e40dd28e85bab
    app.quarkus.io/build-timestamp: 2023-02-20 - 20:49:17 +0000
  labels:
    app: rest-fights
    application: fights-service
    system: quarkus-super-heroes
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: java11-latest
    app.kubernetes.io/part-of: fights-service
    app.kubernetes.io/name: rest-fights
  name: rest-fights
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-fights:java11-latest
      importPolicy: {}
      name: java11-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-fights:java17-latest
      importPolicy: {}
      name: java17-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-fights:native-latest
      importPolicy: {}
      name: native-latest
      referencePolicy:
        type: Source
