---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/connects-to: "villains-db,otel-collector"
    app.openshift.io/vcs-ref: main
    app.quarkus.io/commit-id: f9ba33ded3c72db4f3d1a66c3c0c3de29d993527
    app.quarkus.io/build-timestamp: 2023-01-25 - 16:16:15 +0000
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: rest-villains
    app.kubernetes.io/version: java11-latest
    app.kubernetes.io/part-of: villains-service
  name: rest-villains
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-villains:java11-latest
      importPolicy: {}
      name: java11-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-villains:java17-latest
      importPolicy: {}
      name: java17-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/rest-villains:native-latest
      importPolicy: {}
      name: native-latest
      referencePolicy:
        type: Source
