---
app:
  serviceType: ClusterIP
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 0
    httpGet:
      path: /q/health/live
      scheme: HTTP
      port: 8084
  image: villains-service/rest-villains:java11-latest
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 30
    successThreshold: 1
    initialDelaySeconds: 0
    httpGet:
      path: /q/health/ready
      scheme: HTTP
      port: 8084
