---
app:
  serviceType: ClusterIP
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 5
    httpGet:
      path: /q/health/live
      scheme: HTTP
      port: ":START:{{ .Values.app.livenessProbe.httpGet.port }}:END:"
  image: quay.io/quarkus-super-heroes/rest-fights:java11-latest
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 5
    httpGet:
      path: /q/health/ready
      scheme: HTTP
      port: ":START:{{ .Values.app.readinessProbe.httpGet.port }}:END:"
