---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/connects-to: "fights-kafka,apicurio,otel-collector"
    app.openshift.io/vcs-ref: main
    app.quarkus.io/commit-id: e6b908a2aad15d5f15e203fc2a7e40dd28e85bab
    app.quarkus.io/build-timestamp: 2023-02-20 - 20:49:48 +0000
  labels:
    app: event-statistics
    application: event-stats
    system: quarkus-super-heroes
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: java11-latest
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
  name: event-statistics
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/event-statistics:java11-latest
      importPolicy: {}
      name: java11-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/event-statistics:java17-latest
      importPolicy: {}
      name: java17-latest
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/quarkus-super-heroes/event-statistics:native-latest
      importPolicy: {}
      name: native-latest
      referencePolicy:
        type: Source
